Data_ingestion:
      data: https://github.com/fina-biko/nlp_hate_classification/blob/main/Hate_classification/labeled_data.csv.zip

Data_processing:
      cols_to_drop: ["Unnamed: 0",'count','hate_speech','offensive_language','neither']
      x_col: "tweet"

Feature_engineering:
      x_col: "tweet"
      num_words: 1000
      max_length: 50

Model_training:
      model: LogisticRegression